FROM httpd:2.4.23

MAINTAINER Xavier BEGAULT "xavier.begault@gmail.com"

ADD httpd.conf /usr/local/apache2/conf/httpd.conf
ADD app.conf /usr/local/apache2/conf/extra/httpd-vhosts.conf

WORKDIR /var/www
