FROM httpd:2.4.23

MAINTAINER Xavier BEGAULT "xavier.begault@gmail.com"

#RUN a2enmod rewrite
#ADD app.conf /etc/apache2/sites-available/000-default.conf
ADD app.conf /usr/local/apache2/conf/httpd.conf

WORKDIR /var/www
