version: '2'

services:
    mysql:
        container_name: mysql
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=docker
    php7:
        container_name: php7
        image: php:7.1.0-fpm
        links:
            - mysql
        ports:
            - 9000:9000
        volumes:
            - ..:/var/www/html
    apache:
        container_name: apache
        build: apache
        ports:
            - 90:80
        links:
            - mysql
            - php7
        volumes:
          - ..:/var/www/html
