version: '2'

services:
    x_mysql:
        container_name: x_mysql
        image: mysql:5.7
        ports:
            - "3307:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=docker
    x_php7:
        container_name: x_php7
        image: php:7.1.0-fpm
        links:
            - x_mysql
        ports:
            - 9000:9000
        volumes:
            - ..:/var/www/html
    x_apache:
        container_name: x_apache
        build: apache
        ports:
            - 90:80
        links:
            - x_mysql
            - x_php7
        volumes:
          - ..:/var/www/html
